{% set name = "geodata-harvester" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geodata-harvester-{{ version }}.tar.gz
  sha256: 3b11ca853a80dbce2c7f437ff5ba3f1a44805971478044dccd3221defba8fd80

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - rasterio
    - termcolor
    - xarray
    - matplotlib-base
    - alive-progress >=3.0.1
    - owslib ==0.27.2
    - netcdf4
    - rioxarray
    - pyyaml
    - pandas
    - geopandas
    - pyproj
    - numba
    - shapely
    - fiona >=1.8.21
    - ipywidgets >=7.6.5
    - ipython
    - eeharvest
    - schema
    - requests ==2.28.1

test:
  imports:
    - geodata_harvester
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Sydney-Informatics-Hub/geodata-harvester
  summary: An automation tool for harvesting and processing geodata from the web
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sebhaan
